Clean up error handling for data loading; Fix problem for AttributeError leemdat or leeddat has no attribute 'dat3d'. This was caused by typo where data structure has item dat_3d but GUI code referenced a variable dat3d.